shop/main/routes.py
from flask import render_template, Blueprint
from shop.models import Product
from datetime import datetime, timedelta


main=Blueprint('main', __name__)






@main.route('/')
@main.route('/home')
def home():
    
    # Calculate the date two weeks ago from now
    time_period = datetime.utcnow() - timedelta(hours=48)

    # Query for products created within the last two weeks
    recent_products = Product.query.order_by(Product.created_at.desc()).limit(20).all()
    samsung_products = Product.query.filter(Product.brand == 'samsung').order_by(Product.created_at.desc()).limit(20).all()
    apple_products = Product.query.filter(Product.brand == 'apple').order_by(Product.created_at.desc()).limit(20).all()
    laptop_products = Product.query.filter(Product.category == 'laptop').order_by(Product.created_at.desc()).limit(20).all()
    headphone_products = Product.query.filter(Product.category == 'headphone').order_by(Product.created_at.desc()).limit(20).all()
    watch_products = Product.query.filter(Product.category == 'watch').order_by(Product.created_at.desc()).limit(20).all()
    camera_products = Product.query.filter(Product.category == 'camera').order_by(Product.created_at.desc()).limit(20).all()
    
    
    return render_template('home.html', title = 'Home', recent_products=recent_products, samsung_products=samsung_products,
                           apple_products=apple_products, headphone_products=headphone_products, watch_products=watch_products,
                           camera_products=camera_products, laptop_products=laptop_products)


@main.route('/about')
def about():
    return render_template('about.html', title = 'about')

shop/products/routes.py
from shop import db
from flask import render_template, redirect, flash, url_for, request, abort, Blueprint
from shop.products.forms import AddProductForm, ReviewForm, UpdateProductForm
from shop.models import Product, ProductPicture, Review
from flask_login import current_user, login_required
from datetime import datetime
from sqlalchemy import func
from collections import Counter
from shop.products.utils import add_pictures, ratings



products=Blueprint('products', __name__)

@products.route("/product/new", methods = ['GET', 'POST'])
@login_required
def add_product():
    if current_user.role!='admin':
        abort(403)
    form = AddProductForm()
    if form.validate_on_submit():
        product = Product(
            name=form.name.data,
            description=form.description.data,
            price=form.price.data,
            price_before=form.price_before.data,
            stock=form.stock.data,
            category=form.category.data,
            brand=form.brand.data,
            color=form.color.data,
            size=form.size.data,
            weight=form.weight.data,
            camera=form.camera.data,
            screen=form.screen.data,
            ram=form.ram.data,
            cpu=form.cpu.data,
            gpu=form.gpu.data,
            os=form.os.data,
            storage=form.storage.data,
            battery=form.battery.data,
            note=form.note.data,
            created_at=datetime.utcnow()
        )
        db.session.add(product)
        db.session.commit()
        for img in form.pictures.data:
            picture_name = add_pictures(img)
            picture = ProductPicture(img_url=picture_name, product=product)
            db.session.add(picture)
        db.session.commit()
        flash('The Product has been Added Successfully!', 'success')
        return redirect(url_for('products.product', product_id=product.id))
    return render_template('add_product.html', title='add a product', form=form)



@products.route("/shop/<int:product_id>", methods = ['GET', 'POST'])
def product(product_id):
    product = Product.query.filter_by(id=product_id).first_or_404()
    pictures = ProductPicture.query.filter_by(product_id=product.id)
    specifications = {
            "Color": product.color,
            "Size": product.size,
            "Weight": product.weight,
            "Camera": product.camera,
            "Screen": product.screen,
            "RAM": product.ram,
            "CPU": product.cpu,
            "GPU": product.gpu,
            "OS": product.os,
            "Storage": product.storage,
            "Battery": product.battery,
        }
    
    
    form=ReviewForm()
    if form.validate_on_submit():
        review=Review(
        user_id=current_user.id,
        product_id=product.id,
        rating=int(form.rating.data),
        review=form.review.data,
        created_at=datetime.utcnow()
        )
        db.session.add(review)
        db.session.commit()
        flash('Your Review has been Recorded', 'success')
    
    
    reviews = Review.query.filter_by(product_id=product.id)
    rating=ratings(reviews)
    product.rating=rating
    db.session.commit()
    
    one_rating_count = {}
    for i in range(1, 6):
        one_rating_count[i] = Review.query.filter_by(product_id=product.id, rating=i).count()
    
    rating_count = Review.query.filter_by(product_id=product.id).count()
    
    actual_reviews=Review.query.filter_by(product_id=product.id).limit(16).all()
    
    # Related Products
    related_products = Product.query.filter_by(category=product.category).order_by(func.random()).limit(4).all()
    
    return render_template('product.html', title=product.name, product=product, form=form,
                          pictures=pictures, specifications=specifications
                          , reviews=reviews, rating=rating, one_rating_count=one_rating_count,
                          rating_count=rating_count, actual_reviews=actual_reviews,
                          related_products=related_products)



@products.route('/brands/<string:brand_name>', methods=['GET', 'POST'])
def brand(brand_name):
    
    # Retrieve filters from request parameters
    categories = request.args.getlist('category')
    price_min = request.args.get('price_min', type=float)
    price_max = request.args.get('price_max', type=float)
    
    # Sorting parameters
    sort_by = request.args.get('sort_by', 'price_asc')  # Default sort option
    per_page = request.args.get('per_page', 24, type=int)  # Default per page option
    
    # Define default sort_criteria to avoid NoneType error
    sort_criteria = Product.price.asc()
    
    if sort_by == 'price_desc':
        sort_criteria = Product.price.desc()
    elif sort_by == 'avg_rating':
        sort_criteria = func.avg(Review.rating).desc()
    elif sort_by == 'latest':
        sort_criteria = Product.id.desc()
    

# Query products
    query = Product.query.filter(Product.brand == brand_name)
    
    if categories:
        query = query.filter(Product.category.in_(categories))
    if price_min is not None:
        query = query.filter(Product.price >= price_min)
    if price_max is not None:
        query = query.filter(Product.price <= price_max)

    query = query.order_by(sort_criteria)


    # Pagination logic
    page = request.args.get('page', 1, type=int)
    products = query.paginate(page=page, per_page=per_page, error_out=False)



    # Calculate the count of products in each category for the given brand
    category_counts = db.session.query(Product.category, func.count(Product.id)).filter_by(brand=brand_name).group_by(Product.category).all()
    category_counts_dict = {category: count for category, count in category_counts}
    
    # Total number of products
    total_products_by_brand = query.count()



    return render_template('brand_store.html', products=products, brand_name=brand_name,
                           category_counts=category_counts_dict, total_products=total_products_by_brand,
                           sort_by=sort_by, price_min=price_min, price_max=price_max,
                           per_page=per_page)




@products.route('/category/<string:category_name>')
def category(category_name):
    brands=request.args.getlist('brand')
    price_max=request.args.get('price_max', type=float)
    price_min=request.args.get('price_min', type=float)
    per_page=request.args.get('per_page', 24, type=int)
    sort_by=request.args.get('sort_by', 'price_asc')
    
    
    sort_criteria=Product.price.asc()
    
    if sort_by=='avg_rating':
        sort_criteria=Product.rating.desc()
    elif sort_by=='price_desc':
        sort_criteria=Product.price.desc()
    elif sort_by=='latest':
        sort_criteria=Product.id.desc()
        
    query=Product.query.filter(Product.category==category_name)
    
    if brands:
        query=query.filter(Product.brand.in_(brands))
    if price_max is not None:
        query=query.filter(Product.price <= price_max)
    if price_min is not None:
        query=query.filter(Product.price >= price_min)
        
    query=query.order_by(sort_criteria)
    
    # Pagination
    page = request.args.get('page', 1, type=int)
    products = query.paginate(page=page, per_page=per_page, error_out=False)
    
    
    # Calculate the count of products for each brand for the given category
    brand_counts = db.session.query(Product.brand, func.count(Product.id)).filter_by(category=category_name).group_by(Product.brand).all()
    brand_counts_dict = {brand: count for brand, count in brand_counts}

    # Total number of products
    total_products_by_category = query.count()
    
    return  render_template('category_store.html', products=products, category_name=category_name,
                            brand_counts=brand_counts_dict, total_products=total_products_by_category,
                            sort_by=sort_by, price_min=price_min, price_max=price_max,
                            per_page=per_page)
    
    
@products.route('/search')
def search():
    query = request.args.get('query', '')
    category = request.args.get('category', '')
    sort_by = request.args.get('sort_by', 'latest')
    per_page = request.args.get('per_page', 24, type=int)
    page = request.args.get('page', 1, type=int)
    brands = request.args.getlist('brand')
    price_min = request.args.get('price_min', '')
    price_max = request.args.get('price_max', '')


    # Base query for products
    products_query = Product.query.filter(Product.name.ilike(f'%{query}%') | Product.description.ilike(f'%{query}%'))

    # Apply category filter
    if category:
        products_query = products_query.filter(Product.category == category)


    # Apply price filters
    if price_min:
        products_query = products_query.filter(Product.price >= float(price_min))
    if price_max:
        products_query = products_query.filter(Product.price <= float(price_max))


    # Apply sorting
    if sort_by == 'price_asc':
        products_query = products_query.order_by(Product.price.asc())
    elif sort_by == 'price_desc':
        products_query = products_query.order_by(Product.price.desc())
    elif sort_by == 'avg_rating':
        products_query = products_query.order_by(Product.rating.desc())
    elif sort_by == 'latest':
        products_query = products_query.order_by(Product.created_at.desc())
        
    products_for_count=products_query
    
    # Apply brand filters
    if brands:
        products_query = products_query.filter(Product.brand.in_(brands))

    products = products_query.paginate(page=page, per_page=per_page, error_out=False)

    # Aggregate brand counts for the filtered search results
    # brand_counts={}
    # for product in products:
    #     brand_counts[product.brand] +=1
    
    brand_counts = Counter(product.brand for product in products_for_count)
    print(brand_counts)

    return  render_template('search.html',
                            products=products,

shop/users/routes.py
from shop import bcrypt, db
from flask import render_template, redirect, flash, url_for, request, Blueprint
from shop.users.forms import RegisterationForm, LoginForm, UpdateInformationForm
from shop.models import User
from flask_login import login_user, current_user, logout_user, login_required




users=Blueprint('users', __name__)

@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password_hash=hashed_password, phone=form.phone.data, address=form.address.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title = 'register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password_hash, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title = 'login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account")
@login_required
def account():
    return render_template('account.html', title='Account')


@users.route("/account/information", methods=['GET', 'POST'])
@login_required
def account_information():
    form = UpdateInformationForm()
    if form.validate_on_submit():
        current_user.username=form.username.data
        current_user.email=form.email.data
        current_user.address=form.address.data
        current_user.phone=form.phone.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data=current_user.username
        form.email.data=current_user.email
        form.address.data=current_user.address
        form.phone.data=current_user.phone
    return render_template('account_information.html', title='Update Account Information', form=form)

shop/templates/about.html
{% extends 'layout.html' %} {% block content %}

<div class="content-section">
    <h3>
        <p>There is nothing here, yet!</p>
    </h3>
</div>


{% endblock content %}

shop/templates/account.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="profile-info">
        <h2>{{ current_user.username }}'s Profile</h2>
        <p><strong>Email:</strong> {{ current_user.email }}</p>
        <p><strong>Location:</strong> {{ current_user.address }}</p>
        <!-- Add more user information here as needed -->
      </div>

      <div class="profile-links mt-4">
        <h4>Useful Links</h4>
        <ul class="list-group">
          <li class="list-group-item"><a href="{{url_for('orders.view_orders')}}">Orders</a></li>
          <li class="list-group-item"><a href="{{url_for('users.account_information')}}">Account information</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

shop/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	{% if title %}
	<title>Bruno | {{title}}</title>
	{% else %}
	<title>Bruno</title>
	{% endif %}




	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/slick.css') }}" />
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/slick-theme.css') }}" />
	
	<!-- Website Icon -->
	<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}" />

	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/nouislider.min.css') }}" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
 		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
 		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
 		<![endif]-->

</head>

<body>
	<!-- HEADER -->
	<header>
		<!-- TOP HEADER -->
		<div id="top-header">
			<div class="container">
				<ul class="header-links pull-left">
					<li><a href="tel:00201012345678"><i class="fa fa-phone"></i>01012345678</a></li>
					<li><a href="mailto:brunostore@demo.com"><i class="fa fa-envelope-o"></i>brunostore@demo.com</a></li>
					<li><a href="https://earth.google.com/web/@53.4636016,-2.2892138,32.91330576a,0d,60y,246.08695591h,114.14064371t,0r/data=ChMaEQoJL20vMDMwbHBsGAEgASgCIjAKLEFGMVFpcE5ZTGhZOTBkSmYyZlBUZHhGdWY0N25PN09LVmgwbWF3OUk1Y19JEAU"
							target="_blank"><i class="fa fa-map-marker"></i>Old Trafford, Manchester, UK</a></li>
				</ul>
				<ul class="header-links pull-right">
					{% if current_user.is_authenticated %}
					<li><a href="{{url_for('users.account')}}"><i class="fa fa-user"></i> Account</a></li>
					<li><a href="{{url_for('users.logout')}}"><i class="fa-solid fa-right-from-bracket"></i> Log Out</a></li>
					{% if is_admin(current_user) %}
					<li><a href="{{url_for('products.add_product')}}"><i class="fa-solid fa-desktop"></i> Add a Product</a></li>
					{% endif %}
					{% else %}
					<li><a href="{{url_for('users.register')}}"><i class="fa fa-user-o"></i> Sign Up</a></li>
					<li><a href="{{url_for('users.login')}}"><i class="fa fa-user"></i> Log In</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
		<!-- /TOP HEADER -->

		<!-- MAIN HEADER -->
		<div id="header">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- LOGO -->
					<div class="col-md-3">
						<div class="header-logo">
							<a href="{{url_for('main.home')}}" class="logo">
								<img src="{{ url_for('static', filename='img/logo.png') }}" alt="">
							</a>
						</div>
					</div>
					<!-- /LOGO -->

					<!-- SEARCH BAR -->
					<div class="col-md-6">
						<div class="header-search">
							<form method="GET" action="{{ url_for('products.search') }}">
								<select class="input-select" name="category">
									<option value="">All Categories</option>
									{% for category in categories %}
									<option value="{{ category }}" {% if request.args.get('category')==category
										%}selected{% endif %}>{{ category }}</option>
									{% endfor %}
								</select>
								<input class="input" name="query" placeholder="Search here" {% if
									request.args.get('query') %}value="{{ request.args.get('query') }}" {% endif %}>
								<button class="search-btn" type="submit">Search</button>
							</form>
						</div>
					</div>
					<!-- /SEARCH BAR -->

					<!-- ACCOUNT -->
					<div class="col-md-3 clearfix">
						<div class="header-ctn">
							<!-- Cart -->
							<div class="dropdown">
							    <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
							        <i class="fa fa-shopping-cart"></i>
							        <span>Your Cart</span>
							        <div class="qty">{{ cart_items | length }}</div>
							    </a>
							    <div class="cart-dropdown">
							        <div class="cart-list">
							            {% for item in cart_items %}
							            <div class="product-widget">
							                <div class="product-img">
							                    <img src="{{ url_for('static', filename='img/' ~ item.product.category ~ '.png') }}" alt="{{ item.product.name }}">
							                </div>
							                <div class="product-body">
							                    <h3 class="product-name"><a href="{{ url_for('products.product', product_id=item.product.id) }}">{{ item.product.name }}</a></h3>
							                    <h4 class="product-price"><span class="qty">{{ item.quantity }}x</span>${{ item.product.price }}</h4>
							                </div>
							            </div>
							            {% endfor %}
							        </div>
							        <div class="cart-summary">
							            <small>{{ cart_items | length }} Item(s) selected</small>
							            <h5>SUBTOTAL: ${{ cart_total }}</h5>
							        </div>
							        <div class="cart-btns">
							            <a href="{{ url_for('orders.view_cart') }}">View Cart</a>
							            <a href="{{ url_for('orders.checkout')}}">Checkout <i class="fa fa-arrow-circle-right"></i></a>
							        </div>
							    </div>
							</div>
							<!-- /Cart -->


							<!-- Menu Toogle -->
							<div class="menu-toggle">
								<a href="#">
									<i class="fa fa-bars"></i>
									<span>Menu</span>
								</a>
							</div>
							<!-- /Menu Toogle -->
						</div>
					</div>
					<!-- /ACCOUNT -->
				</div>
				<!-- row -->
			</div>
			<!-- container -->
		</div>
		<!-- /MAIN HEADER -->
	</header>
	<!-- /HEADER -->

	<!-- NAVIGATION -->
	<nav id="navigation">
		<!-- container -->
		<div class="container">
			<!-- responsive-nav -->
			<div id="responsive-nav">
				<!-- NAV -->
				<ul class="main-nav nav navbar-nav">
					<li class="active"><a href="{{url_for('main.home')}}">Home</a></li>
					<li><a href="{{url_for('products.category',category_name='smartphone')}}">Smartphones</a></li>
					<li><a href="{{url_for('products.category',category_name='laptop')}}">Laptops</a></li>
					<li><a href="{{url_for('products.category',category_name='camera')}}">Cameras</a></li>
					<li><a href="{{url_for('products.category',category_name='watch')}}">Watches</a></li>
					<li><a href="{{url_for('products.category',category_name='accessory')}}">Accessories</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
							aria-expanded="false">Brands <span class="caret"></span></a>
						<ul class="dropdown-menu">
							{% for brand in brands %}
							<li><a href="{{ url_for('products.brand', brand_name=brand) }}">{{ brand }}</a></li>
							{% endfor %}
						</ul>
					</li>
				</ul>
				<!-- /NAV -->
			</div>
			<!-- /responsive-nav -->
		</div>
		<!-- /container -->
	</nav>
	<!-- /NAVIGATION -->
	{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	{% for category, message in messages %}
	<div class="alert alert-{{ category }} text-center">
		{{ message }}
	</div>
	{% endfor %}
	{% endif %}
	{% endwith %}

	<main>
		<section class="content-section">
			<div class="container">
				{% block content %}
				{% endblock %}
			</div>
		</section>
	</main>



	<!-- FOOTER -->
	<footer id="footer">
		<!-- top footer -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">About Us</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
								incididunt ut.</p>
							<ul class="footer-links">
								<li><a href="tel:00201012345678"><i class="fa fa-phone"></i>01012345678</a></li>
								<li><a href="mailto:brunostore@demo.com"><i class="fa fa-envelope-o"></i>brunostore@demo.com</a></li>
								<li><a href="https://earth.google.com/web/@53.4636016,-2.2892138,32.91330576a,0d,60y,246.08695591h,114.14064371t,0r/data=ChMaEQoJL20vMDMwbHBsGAEgASgCIjAKLEFGMVFpcE5ZTGhZOTBkSmYyZlBUZHhGdWY0N25PN09LVmgwbWF3OUk1Y19JEAU"
									target="_blank"><i class="fa fa-map-marker"></i>Old Trafford, Manchester, UK</a></li>
							</ul>
						</div>
					</div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Links</h3>
							<ul class="footer-links">
								<li><a href="{{url_for('products.category',category_name='smartphone')}}">Smartphones</a></li>
								<li><a href="{{url_for('products.category',category_name='laptop')}}">Laptops</a></li>
								<li><a href="{{url_for('products.category',category_name='pc')}}">PCs</a></li>
								<li><a href="{{url_for('products.category',category_name='camera')}}">Cameras</a></li>
								<li><a href="{{url_for('products.category',category_name='accessory')}}">Accessories</a></li>
							</ul>
						</div>
					</div>

					<div class="clearfix visible-xs"></div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Information</h3>
							<ul class="footer-links">
								<li><a href="{{url_for('main.about')}}">About Us</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Orders and Returns</a></li>
								<li><a href="#">Terms & Conditions</a></li>
							</ul>
						</div>
					</div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Service</h3>
							<ul class="footer-links">
								<li><a href="{{url_for('users.account')}}">My Account</a></li>
								<li><a href="{{ url_for('orders.view_cart') }}">View Cart</a></li>
								<li><a href="{{url_for('orders.view_orders')}}">My Orders</a></li>
								<li><a href="{{url_for('users.account_information')}}">Account Information</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /top footer -->

		<!-- bottom footer -->
		<div id="bottom-footer" class="section">
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12 text-center">
						<ul class="footer-payments">
							<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
							<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
						</ul>
						<span class="copyright">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;
							<script>document.write(new Date().getFullYear());</script> All rights reserved | This
							template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
								href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</span>


					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /bottom footer -->
	</footer>
	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/slick.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/nouislider.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.zoom.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/main.js') }}"></script>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.0/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<script src="https://kit.fontawesome.com/e99702310e.js" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


</body>

</html>